In [1]:
import pandas as pd

In [2]:
place = pd.read_csv('Top Indian Places to Visit.csv')

In [16]:
(place.head())

,Unnamed: 0,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,Weekly Off,Significance,DSLR Allowed,Number of google review in lakhs,Best Time to visit
0,0,Northern,Delhi,Delhi,India Gate,War Memorial,1921,0.5,4.6,0,Yes,NaN,Historical,Yes,2.60,Evening
1,1,Northern,Delhi,Delhi,Humayun's Tomb,Tomb,1572,2.0,4.5,30,Yes,NaN,Historical,Yes,0.40,Afternoon
2,2,Northern,Delhi,Delhi,Akshardham Temple,Temple,2005,5.0,4.6,60,Yes,NaN,Religious,No,0.40,Afternoon
3,3,Northern,Delhi,Delhi,Waste to Wonder Park,Theme Park,2019,2.0,4.1,50,Yes,Monday,Environmental,Yes,0.27,Evening
4,4,Northern,Delhi,Delhi,Jantar Mantar,Observatory,1724,2.0,4.2,15,Yes,NaN,Scientific,Yes,0.31,Morning

In [19]:
place.shape

(325, 16)

In [20]:
def rank_weekend_places(city_name):
   
    city_data = place[place['City'].str.contains(city_name, case=False, na=False)]
    city_data_sorted = city_data.sort_values(by='Google review rating', ascending=False)
    return city_data_sorted[['Name', 'Type', 'Google review rating', 'Entrance Fee in INR', 'time needed to visit in hrs', 'Best Time to visit']]

In [21]:
city_name = "Kolkata"
ranked_places = rank_weekend_places(city_name)


(ranked_places)

,Name,Type,Google review rating,Entrance Fee in INR,time needed to visit in hrs,Best Time to visit
50,Belur Math,Site,4.7,0,1.5,Morning
45,Dakshineswar Kali Temple,Temple,4.7,0,1.0,Morning
43,Howrah Bridge,Bridge,4.6,0,0.5,Anytime
42,Victoria Memorial,Museum,4.6,30,1.5,Morning
44,Indian Museum,Museum,4.6,50,2.0,Morning
46,Kalighat Kali Temple,Temple,4.4,0,1.0,Morning
51,Marble Palace,Palace,4.4,0,1.0,Afternoon
49,Science City Kolkata,Science,4.4,60,3.0,All
48,Alipore Zoological Gardens,Zoo,4.3,25,2.0,Afternoon
47,Eden Gardens,Cricket Ground,4.1,2500,3.0,All